apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrk-mealplan-webapi
spec:
  template:
    spec:
      initContainers:
      - name: init-mongodb
        env:
        - name: MEALPLAN_API_MONGODB_HOST
          value: null
          valueFrom:
            configMapKeyRef:
              name: mongodb-connection
              key: host
        - name: MEALPLAN_API_MONGODB_PORT
          value: null
          valueFrom:
            configMapKeyRef:
              name: mongodb-connection
              key: port
        - name: MEALPLAN_API_MONGODB_USERNAME
          value: null
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: username
        - name: MEALPLAN_API_MONGODB_PASSWORD
          value: null
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: password
      containers:
      - name: rrk-mealplan-webapi-container
        env:
        - name: MEALPLAN_API_MONGODB_HOST
          value: null
          valueFrom:
            configMapKeyRef:
              name: mongodb-connection
              key: host
        - name: MEALPLAN_API_MONGODB_PORT
          value: null
          valueFrom:
            configMapKeyRef:
              name: mongodb-connection
              key: port
        - name: MEALPLAN_API_MONGODB_USERNAME
          value: null
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: username
        - name: MEALPLAN_API_MONGODB_PASSWORD
          value: null
          valueFrom:
            secretKeyRef:
              name: mongodb-auth
              key: password
