kind: Service
apiVersion: v1
metadata:
  name: rrk-mealplan-webapi
spec:
  selector:
    pod: rrk-mealplan-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port
