/*
 * Hospital Meal Plan Management API
 *
 * API to manage meals, patients, and their meal plans in a hospital.
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mealplan

// MealNutrients - Nutritional content per serving
type MealNutrients struct {

	Fats float32 `json:"fats,omitempty"`

	Carbohydrates float32 `json:"carbohydrates,omitempty"`

	Proteins float32 `json:"proteins,omitempty"`

	Calories int32 `json:"calories,omitempty"`
}
