/*
 * Hospital Meal Plan Management API
 *
 * API to manage meals, patients, and their meal plans in a hospital.
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mealplan

type MealPlanMealsInner struct {

	MealId string `json:"mealId,omitempty"`

	Time string `json:"time,omitempty"`
}
