/*
 * Hospital Meal Plan Management API
 *
 * API to manage meals, patients, and their meal plans in a hospital.
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mealplan

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newMealPlansAPI()
    api.addRoutes(group)
  }
  
  {
    api := newMealsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newPatientsAPI()
    api.addRoutes(group)
  }
  
}